openapi: 3.0.0
info:
  title: Tickets API
  description: API documentation for managing tickets.
  version: 1.0.0

paths:
  /api/tickets/{nid}:
    get:
      summary: Get ticket by user ID
      parameters:
        - name: nid
          in: path
          required: true
          schema:
            type: string
          description: The user ID to get the ticket for.
      responses:
        200:
          description: Ticket details
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  response:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                          example: "5f8d0d55b54764421b7156c1"
                        total:
                          type: number
                          example: 150.00
                        date:
                          type: string
                          format: date-time
                          example: "2023-01-01T00:00:00.000Z"
        400:
          description: Bad request
        404:
          description: Ticket not found
